name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      # Trigger when a comment is created on an issue and mentions '@claude'
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      # Trigger when a comment is created on a pull request review and mentions '@claude'
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      # Trigger when a pull request review is submitted and mentions '@claude'
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      # Trigger when an issue is opened or assigned, and the body or title mentions '@claude'
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

